### PR TITLE
Switch to mapparser lib

### LINKED ISSUE #182: add zstd parser/decompressor for the new mapblock format
* PR: https://github.com/minetest/minetest/pull/10788
* Golang library: https://pkg.go.dev/github.com/klauspost/compress/zstd

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
* Will fix #182 and #217

### CODE REVIEW

**Comment by TEbinger** [comment]
What is missing to accept this PR? It would be great to use mapserver with minetest 5.5 again

**Comment by BuckarooBanzay** [comment]
> What is missing to accept this PR? It would be great to use mapserver with minetest 5.5 again

not sure, i think i was refactoring parts of the mapblock-position handling inside the returned mapblock data itself (the new library is position-agnostic and stores it nowhere) and somehow lost the motivation :shrug: 

can't promise anything but i think i'll get this done around the next mt release (5.5) whenever that is :)
if you want you can try to help :wink: go is a pretty nice language

**Comment by TEbinger** [comment]
I am not a programmer, but I could test it with our 5.5-dev minetest server (minetestbildungsserver in the server list) if I can get access to a beta version and give You bug reports.

**Comment by BuckarooBanzay** [comment]
> I am not a programmer, but I could test it with our 5.5-dev minetest server (minetestbildungsserver in the server list) if I can get access to a beta version and give You bug reports.

I managed to get this into a working state (was easier than i thought) about the beta-testing: how do you run the mapserver?
Do you have a container-setup or are you running this "old-school" with a simple binary?

**Comment by TEbinger** [comment]
We just use the binary.

**Comment by BuckarooBanzay** [comment]
> We just use the binary. How can I get it?

I created a pre-release here: https://github.com/minetest-mapserver/mapserver/releases/tag/4.5.0-rc1
Works in all my test-worlds (zstd and non-zstd)

**Comment by TEbinger** [comment]
Wonderful. Everything works and the map is rendering now. See the result at http://136.243.82.83:8080/ . Thank You very much! Yesterday Minetest 5.5 was officially released, so it's perfect to see it working now again.

**Pull request merged**
